clothes/urls.py
from django.urls import path

from . import views

app_name = 'clothes'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/<str:type>/', views.home, name='home'),
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_cart_item/', views.add_cart_item, name='add_cart_item'),
    path('del_cart_item/<int:product_item_id>/',
         views.del_cart_item, name='del_cart_item'),
    path('cart_view/', views.cart_view, name='cart_view'),
    path('order_view/', views.order_view, name='order_view'),
    path('order_view/<int:item_id>/', views.order_view, name='order_view'),
    path('order/', views.order, name='order'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('clothes.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothes/models.py
from django.db import models
from django.forms import CharField


class Product_type(models.Model):
    product_type = models.CharField(max_length=200, unique=True)

    def __str__(self) -> str:
        return self.product_type


class Product_size(models.Model):
    product_size = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.product_size


class Product(models.Model):
    product_name = models.TextField(max_length=200)

    image = models.ImageField(upload_to="images/")
    price = models.IntegerField()
    product_type = models.ForeignKey(Product_type, on_delete=models.CASCADE)
    product_size = models.ManyToManyField(Product_size)

    def __str__(self):
        return self.product_name


class User(models.Model):
    user_name = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=200)
    phone = models.CharField(max_length=200, unique=True)
    email = models.EmailField(max_length=254, unique=True)
    full_name = models.CharField(max_length=200)

    def __str__(self):
        return self.user_name


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_name_receive = models.CharField(max_length=200)
    phone_receive = models.CharField(max_length=200)
    address_receive = models.CharField(max_length=200)
    sum_price = models.IntegerField()

    def __str__(self):
        return self.user_name_receive


class Cart_item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_size = models.ForeignKey(Product_size, on_delete=models.CASCADE)
    number_product = models.IntegerField()
    sum_price = models.IntegerField()

    def __str__(self):
        return self.product.product_name


class Order_item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_size = models.ForeignKey(Product_size, on_delete=models.CASCADE)
    number_product = models.IntegerField()
    sum_price = models.IntegerField()

    def __str__(self):
        return self.product.product_name

clothes/views.py
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from .models import Cart_item, Product_size, Product_type, User, Product, Order, Order_item
from django.contrib import messages


def home(request, type=""):
    # Create session type_list
    if 'user_id' not in request.session:
        request.session['user_id'] = -1
    if 'user_name' not in request.session:
        request.session['user_name'] = ""
    request.session.modified = True
    if 'type_list' not in request.session:
        request.session['type_list'] = []
        type_list = Product_type.objects.all()
        for type in type_list:
            request.session['type_list'].insert(0, type.product_type)
    request.session.modified = True

    if request.method == 'POST':
        search = request.POST['search']
        product_list = Product.objects.filter(product_name__contains=search)
        context = {
            'product_list': product_list,
        }
    else:
        if type == "":
            product_list = Product.objects.all()
            context = {
                'product_list': product_list,
            }
        else:
            product_type = get_object_or_404(Product_type, product_type=type)
            product_list = product_type.product_set.all()
            context = {
                'product_list': product_list,
            }
    return render(request, template_name='clothes/home.html', context=context)


def register(request):
    if request.method == 'POST':
        new_user = User()
        new_user.user_name = request.POST['user_name']
        new_user.password = request.POST['password']
        new_user.phone = request.POST['phone']
        new_user.email = request.POST['email']
        new_user.full_name = request.POST['full_name']
        try:
            new_user.save()
            request.session['user_id'] = new_user.id
            request.session['user_name'] = new_user.user_name
            request.session.modified = True
            return redirect('clothes:home')
        except IntegrityError as e:
            messages.error(
                request, ("User name, phone number or email address already exits!"))
            return redirect('clothes:register')
    else:
        return render(request, 'clothes/register.html')


def login(request):
    if request.method == 'POST':
        user_name = request.POST['user_name']
        password = request.POST['password']
        try:
            user = User.objects.get(user_name=user_name, password=password)
            request.session['user_id'] = user.id
            request.session['user_name'] = user.user_name
            request.session.modified = True
            return redirect('clothes:home')
        except:
            messages.error(request, ("User name or password incorrect!"))
            return redirect('clothes:login')
    else:
        return render(request, 'clothes/login.html')


def logout(request):
    request.session['user_id'] = -1
    return redirect('clothes:home')


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request=request, template_name='clothes/product_detail.html', context={'product': product})


def add_cart_item(request):
    product_id = request.POST['product_id']
    size_id = request.POST['size_id']
    number = request.POST['number']

    if request.session['user_id'] != -1:
        user = get_object_or_404(User, pk=request.session['user_id'])
        # cart_list = user.cart_item_set.all()
        # for item in cart_list:
        #     if item.product.id == product_id and item.product_size.id == size_id:
        #         item.number_product += number
        #         item.save()
        #         break
        # else:
        product = get_object_or_404(Product, pk=product_id)
        product_size = get_object_or_404(Product_size, pk=size_id)
        sum_price = product.price * int(number)
        cart_item = Cart_item(
            product=product, user=user, product_size=product_size, number_product=number, sum_price=sum_price)
        cart_item.save()
        messages.success(
            request, ("Thêm vào giỏ hàng thành công."))
        return redirect('clothes:product_detail', product_id=product_id)


def del_cart_item(request, product_item_id):
    Cart_item.objects.get(pk=product_item_id).delete()
    return redirect('clothes:cart_view')


def cart_view(request):
    if request.session['user_id'] != -1:
        user = User.objects.get(pk=request.session['user_id'])
        cart_list = user.cart_item_set.all()
        context = {
            'cart_list': cart_list,
        }
        return render(request, template_name='clothes/cart.html', context=context)
    else:
        return redirect('clothes:login')


def order_view(request, item_id=-1):
    if request.session['user_id'] != -1:
        user = User.objects.get(pk=request.session['user_id'])
        if item_id == -1:
            product_id = request.POST['product_id']
            size_id = request.POST['size_id']
            number = request.POST['number']
            product = get_object_or_404(Product, pk=product_id)
            product_size = get_object_or_404(Product_size, pk=size_id)
            sum_price = product.price * int(number)
            order_item = Order_item(
                product=product, product_size=product_size, number_product=number, sum_price=sum_price)
            context = {
                'order_item': order_item,
                'user': user
            }
        else:
            order_item = Cart_item.objects.get(pk=item_id)
            context = {
                'order_item': order_item,
                'user': user
            }
        return render(request, template_name='clothes/order.html', context=context)
    else:
        return redirect('clothes:login')


def order(request):
    if request.session['user_id'] != -1:
        user = User.objects.get(pk=request.session['user_id'])
        user_name_receive = request.POST['user_name_receive']
        address_receive = request.POST['address_receive']
        phone_receive = request.POST['phone_receive']
        product_id = request.POST['product_id']
        size = request.POST['product_size']
        number_product = request.POST['number_product']
        product = get_object_or_404(Product, pk=product_id)
        product_size = get_object_or_404(Product_size, product_size=size)
        sum_price = product.price * int(number_product)
        order = Order(user=user, user_name_receive=user_name_receive,
                      phone_receive=phone_receive, address_receive=address_receive, sum_price=sum_price)
        order.save()
        order_item = Order_item(
            product=product, order=order, product_size=product_size, number_product=number_product, sum_price=sum_price)
        order_item.save()
        messages.success(request, "Đặt hàng thành công.")
        return redirect('clothes:home')
    else:
        return redirect('clothes:login')

clothes/templates/clothes/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Clothes Shop</title>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
            crossorigin="anonymous"
        />
    </head>
    <body>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none">
            <symbol
                id="check-circle-fill"
                fill="currentColor"
                viewBox="0 0 16 16"
            >
                <path
                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"
                />
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path
                    d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"
                />
            </symbol>
            <symbol
                id="exclamation-triangle-fill"
                fill="currentColor"
                viewBox="0 0 16 16"
            >
                <path
                    d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
                />
            </symbol>
        </svg>
        {% include 'clothes/navbar.html' %}
        <br />

        {% if messages %}
        <div class="container">
            {% for message in messages %}
            <!-- block if -->
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div
                class="alert alert-warning alert-dismissible fade show"
                role="alert"
            >
                <svg
                    class="bi flex-shrink-0 me-2"
                    width="24"
                    height="24"
                    role="img"
                    aria-label="Warning:"
                >
                    <use xlink:href="#exclamation-triangle-fill" />
                </svg>
                {{ message }}
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"
                ></button>
            </div>
            {% else %}
            <div
                class="alert alert-success alert-dismissible fade show"
                role="alert"
            >
                <svg
                    class="bi flex-shrink-0 me-2"
                    width="24"
                    height="24"
                    role="img"
                    aria-label="Success:"
                >
                    <use xlink:href="#check-circle-fill" />
                </svg>
                {{ message }}
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"
                ></button>
            </div>
            {% endif %} {% endfor %}
        </div>
        {% endif %} {% block content %} {% endblock %}
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

clothes/templates/clothes/cart.html
{% extends 'clothes/base.html' %} {% block content %} {% if cart_list %}
<div class="container-fluid">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for item in cart_list %}
        <div class="g-col-6">
            <div class="card mb-3" style="max-width: 540px">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img
                            src="{{ item.product.image.url }}"
                            class="img-fluid rounded-start"
                            alt="..."
                        />
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h6
                                class="card-title"
                                style="
                                    overflow: hidden;
                                    text-overflow: ellipsis;
                                    display: -webkit-box;
                                    -webkit-line-clamp: 1; /* number of lines to show */
                                    -webkit-box-orient: vertical;
                                "
                            >
                                {{ item.product.product_name }}
                            </h6>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Tổng giá: {{ item.sum_price }}
                                </li>
                                <li class="list-group-item">
                                    Số lượng: {{ item.number_product }}
                                </li>
                                <li class="list-group-item">
                                    Size: {{ item.product_size }}
                                </li>
                            </ul>
                            <a
                                href="{% url 'clothes:del_cart_item' item.id %}"
                                class="btn btn-primary"
                                >Xóa</a
                            >
                            <a
                                href="{% url 'clothes:order_view' item.id %}"
                                class="btn btn-primary"
                                >Mua hàng</a
                            >
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% else %}
<p>No item are available.</p>
{% endif %} {% endblock %}

clothes/templates/clothes/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Clothes Shop</title>
    </head>
    <body>
        <a href="{% url 'clothes:register' %}">Register here</a>
    </body>
</html>

clothes/templates/clothes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'clothes:home' %}">Home</a>
        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"
                        >Home</a
                    >
                </li> -->
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#"
                        id="navbarDropdown"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                    >
                        Type
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for item in request.session.type_list %}
                        <li>
                            <a
                                class="dropdown-item"
                                href="{% url 'clothes:home' item %}"
                                >{{ item }}</a
                            >
                        </li>
                        <li><hr class="dropdown-divider" /></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clothes:cart_view' %}"
                        >Cart</a
                    >
                </li>
                {% if request.session.user_id == -1 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clothes:login' %}"
                        >Login</a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clothes:register' %}"
                        >Register</a
                    >
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#"
                        >{{ request.session.user_name }}</a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clothes:logout' %}"
                        >Logout</a
                    >
                </li>
                {% endif %}
                <!-- <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li> -->
            </ul>
            <form
                class="d-flex"
                role="search"
                action="{% url 'clothes:home' %}"
                method="post"
            >
                {% csrf_token %}
                <input
                    class="form-control me-2"
                    type="search"
                    name="search"
                    placeholder="Search"
                    aria-label="Search"
                />
                <button class="btn btn-outline-success" type="submit">
                    Search
                </button>
            </form>
        </div>
    </div>
</nav>

clothes/templates/clothes/order.html
{% extends 'clothes/base.html' %} {% block content %} {% if order_item %}
<div class="container">
    <center><h1>Order</h1></center>
    <br />
    <form action="{% url 'clothes:order' %}" method="post">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="user_name_receive"
                id="user_name_receive"
                value="{{ user.full_name }}"
                placeholder="Tên người nhận"
                required
            />
            <label for="user_name_receive" class="form-label"
                >Tên người nhận</label
            >
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="address_receive"
                id="address_receive"
                placeholder="Địa chỉ nhận hàng"
                required
            />
            <label for="address_receive" class="form-label"
                >Địa chỉ nhận hàng</label
            >
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="phone_receive"
                id="phone_receive"
                value="{{ user.phone }}"
                placeholder="Số điện thoại nhận hàng"
                required
            />
            <label for="phone_receive" class="form-label"
                >Số điện thoại nhận hàng</label
            >
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="product_id"
                id="product_id"
                value="{{ order_item.product.id }}"
                readonly
                hidden
            />
            <label for="product_id" class="form-label">ID sản phẩm</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="product_name"
                id="product_name"
                value="{{ order_item.product.product_name }}"
                readonly
            />
            <label for="product_name" class="form-label">Tên sản phẩm</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="number"
                class="form-control"
                name="number_product"
                id="number_product"
                value="{{ order_item.number_product }}"
                readonly
            />
            <label for="number_product" class="form-label"
                >Số lượng sản phẩm</label
            >
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="product_size"
                id="product_size"
                value="{{ order_item.product_size }}"
                readonly
            />
            <label for="product_size" class="form-label">Size</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                name="sum_price"
                id="sum_price"
                value="{{ order_item.sum_price }}&#8363;"
                readonly
            />
            <label for="sum_price" class="form-label">Tổng số tiền</label>
        </div>
        <button type="submit" class="btn btn-primary">Đặt hàng</button>
    </form>
</div>
{% endif %} {% endblock %}

clothes/templates/clothes/product_detail.html
{% extends 'clothes/base.html' %} {% block content %} {% load static %}
<body>
    {{ product.id|json_script:"product_id" }}
    <div style="margin-right: 65px; margin-left: 65px">
        <div class="row gx-3">
            <div class="col">
                <img src="{{ product.image.url }}" alt="" />
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <h6
                            class="card-subtitle mb-2 text-muted"
                            style="margin-top: 10px"
                        >
                            Giá: {{ product.price }}&#8363;
                        </h6>
                        <form
                            action="{% url 'clothes:add_cart_item' %}"
                            method="post"
                        >
                            {% csrf_token %}
                            <input
                                type="text"
                                name="product_id"
                                value="{{ product.id }}"
                                hidden
                            />
                            <h6
                                class="card-subtitle mb-2 text-muted"
                                style="margin-top: 20px"
                            >
                                Kích thước
                            </h6>
                            <div class="card d-inline-flex">
                                <div class="col">
                                    {% for size in product.product_size.all%}
                                    <div class="form-check form-check-inline">
                                        <input
                                            type="radio"
                                            name="size_id"
                                            id="size{{ forloop.counter }}"
                                            value="{{ size.id }}"
                                            required
                                        />
                                        <label
                                            class="form-check-label"
                                            for="size{{ forloop.counter }}"
                                            >{{ size.product_size}}</label
                                        >
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div style="margin-top: 10px">
                                <a
                                    href="#"
                                    class="card-subtitle mb-2 text-muted"
                                    style="margin-top: 50px"
                                    data-bs-toggle="modal"
                                    data-bs-target="#Modal"
                                >
                                    Hướng dẫn đo kích thước
                                </a>
                            </div>
                            <div class="mb-3" style="margin-top: 20px">
                                <label for="number" class="form-label"
                                    >Số lượng sản phẩm</label
                                >
                                <input
                                    type="number"
                                    class="form-control"
                                    id="number"
                                    name="number"
                                    min="1"
                                    max="100"
                                    required
                                    placeholder="1"
                                    style="width: 150px"
                                />
                            </div>
                            <div
                                style="
                                    display: flex;
                                    justify-content: center;
                                    margin-top: 20px;
                                "
                            >
                                <input
                                    class="btn btn-warning"
                                    type="submit"
                                    value="Thêm vào giỏ hàng"
                                    style="margin-right: 20px"
                                />
                                <input
                                    class="btn btn-danger"
                                    type="submit"
                                    formaction="{% url 'clothes:order_view' %}"
                                    value="Mua ngay"
                                />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div
        class="modal fade"
        id="Modal"
        tabindex="-1"
        aria-labelledby="Modal"
        aria-hidden="true"
    >
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">
                        Hướng dẫn đo kích thước
                    </h5>
                </div>
                <div class="modal-body">
                    <img
                        src="{% static '/images/size.jpg' %}"
                        class="img-fluid"
                        alt=""
                    />
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}